project:
  type: book
  output-dir: docs

book:
  title: "Metrics Notes"
  author: "Norah Jones"
  date: "5/14/2025"
  chapters:
    - index.qmd
    - probability_theory.qmd
    - conditional_expectation.qmd
    - measure_theory.qmd
    - part: "Time Series"
      chapters:
        - TS01_AR1.qmd
        - TS01_AR_example.qmd
        - TS01_phillips-curve.qmd
        - TS01_properties_AR1Errors.qmd
        - TS01_Correct_AR1Errors.qmd
        - TS01_examples.qmd
        - TS02_lag_poly.qmd
        - TS02_AR-MA-representation.qmd
        - TS03_finite-property.qmd
        - TS03_asymptotic-property.qmd
        - TS04_TimeSeries_regression.qmd
        - TS04_Spurious_regression.qmd
        - TS04_highly-persistent.qmd
        - TS05_Forecast.qmd
    - part: "Panel Data"
      chapters:
        - PA01_Pooled_regression.qmd
        - PA02_Panel_regression.qmd
        - PA03_Fixed-Effects.qmd
        - PA04_Random-Effects.qmd
        - PA05_dynamic_models.qmd
        - PA06_dynamic_models_with_pdynmc.qmd
        - PA07_Hetero_lm.qmd
        

bibliography: metrics.bib

format:
  html:
    include-in-header: themes/mathjax.html
    respect-user-color-scheme: true
    theme:
      dark: [cosmo, themes/cosmo-dark.scss]
      light: [cosmo, themes/cosmo-light.scss]
crossref: 
  cnj-title: "Assumption"
  cnj-prefix: "Assumption"



