project:
  type: book
  output-dir: docs

book:
  title: "Metrics Notes"
  author: "Norah Jones"
  date: "5/14/2025"
  chapters:
    - index.qmd
    - probability_theory.qmd
    - conditional_expectation.qmd
    - measure_theory.qmd
    - 01_Hetero_lm.qmd

bibliography: metrics.bib

format:
  html:
    include-in-header: themes/mathjax.html
    theme:
      - cosmo
      - brand



