project:
  type: book
  output-dir: docs

book:
  title: "Metrics Notes"
  author: "Norah Jones"
  date: "5/14/2025"
  chapters:
    - index.qmd
    - probability_theory.qmd
    - conditional_expectation.qmd
    - measure_theory.qmd
    - part: "Time Series"
      chapters:
        - AR1.qmd
        - AR_example.qmd
        - lag_poly.qmd
        - AR-MA-representation.qmd
    - 01_Hetero_lm.qmd

bibliography: metrics.bib

format:
  html:
    include-in-header: themes/mathjax.html
    respect-user-color-scheme: true
    theme:
      dark: [cosmo, themes/cosmo-dark.scss]
      light: cosmo



