<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>17&nbsp; Spurious Regression – Metrics Notes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./TS04_highly-persistent.html" rel="next">
<link href="./TS04_VAR.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-e1a5c8363afafaef2c763b6775fbf3ca.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-8ef56b68f8fa1e9d2ba328e99e439f80.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-a4d0c9c7c01e9e8ad6d051bd73593869.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-95b79468fb1b275d35eccd7531d6cfe2.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
 
<!-- This is what works with Quarto and MathJax 3+ -->
<script>
  MathJax = {
    tex: {
      inlineMath: [   // start/end delimiter pairs for in-line math
          ['$', '$'],
          ['\\(', '\\)']
        ],
      displayMath: [  // start/end delimiter pairs for display math
        ['$$', '$$'],
        ['\\[', '\\]']
      ],
      processEscapes: true, // use \$ to produce a literal dollar sign
      tags: 'ams',  // should be 'ams', 'none', or 'all'
      macros: {  //define TeX macros
        bold: ["{\\boldsymbol #1}", 1],  // use \bold as a shorthand
        indep: "{\\perp \\!\\!\\! \\perp}",
        vect: ["\\mathbf{#1}", 1],
        mat: ["\\mathbf{#1}", 1], 

        bA: "\\boldsymbol{A}",
        bB: "\\boldsymbol{B}",
        bC: "\\boldsymbol{C}",
        bD: "\\boldsymbol{D}",
        bE: "\\boldsymbol{E}",
        bF: "\\boldsymbol{F}",
        bG: "\\boldsymbol{G}",
        bH: "\\boldsymbol{H}",
        bI: "\\boldsymbol{I}",
        bJ: "\\boldsymbol{J}",
        bK: "\\boldsymbol{K}",
        bL: "\\boldsymbol{L}",
        bM: "\\boldsymbol{M}",
        bN: "\\boldsymbol{N}",
        bP: "\\boldsymbol{P}",
        bQ: "\\boldsymbol{Q}",
        bR: "\\boldsymbol{R}",
        bS: "\\boldsymbol{S}",
        bT: "\\boldsymbol{T}",
        bU: "\\boldsymbol{U}",
        bV: "\\boldsymbol{V}",
        bW: "\\boldsymbol{W}",
        bX: "\\boldsymbol{X}",
        bY: "\\boldsymbol{Y}",
        bZ: "\\boldsymbol{Z}",
        
        ba: "\\boldsymbol{a}",
        bb: "\\boldsymbol{b}",
        bc: "\\boldsymbol{c}",
        bd: "\\boldsymbol{d}",
        be: "\\boldsymbol{e}",
        bg: "\\boldsymbol{g}",
        bh: "\\boldsymbol{h}",
        bi: "\\boldsymbol{i}",
        bm: "\\boldsymbol{m}",
        bp: "\\boldsymbol{p}",
        bq: "\\boldsymbol{q}",
        br: "\\boldsymbol{r}",
        bs: "\\boldsymbol{s}",
        bt: "\\boldsymbol{t}",
        bu: "\\boldsymbol{u}",
        bv: "\\boldsymbol{v}",
        bw: "\\boldsymbol{w}",
        bx: "\\boldsymbol{x}",
        by: "\\boldsymbol{y}",
        bz: "\\boldsymbol{z}",

        Acal: "\\mathcal{A}",
        Bcal: "\\mathcal{B}",
        Ccal: "\\mathcal{C}",
        Dcal: "\\mathcal{D}",
        Ecal: "\\mathcal{E}",
        Fcal: "\\mathcal{F}",
        Gcal: "\\mathcal{G}",
        Hcal: "\\mathcal{H}",
        Ical: "\\mathcal{I}",
        Jcal: "\\mathcal{J}",
        Kcal: "\\mathcal{K}",
        Lcal: "\\mathcal{L}",
        Mcal: "\\mathcal{M}",
        Ncal: "\\mathcal{N}",
        Ocal: "\\mathcal{O}",
        Pcal: "\\mathcal{P}",
        Qcal: "\\mathcal{Q}",
        Rcal: "\\mathcal{R}",
        Scal: "\\mathcal{S}",
        Tcal: "\\mathcal{T}",
        Ucal: "\\mathcal{U}",
        Vcal: "\\mathcal{V}",
        Wcal: "\\mathcal{W}",
        Xcal: "\\mathcal{X}",
        Ycal: "\\mathcal{Y}",
        Zcal: "\\mathcal{Z}",

        A: "\\mathbb{A}",
        B: "\\mathbb{B}",
        C: "\\mathbb{C}",
        D: "\\mathbb{D}",
        E: "\\mathbb{E}",
        F: "\\mathbb{F}",
        G: "\\mathbb{G}",
        H: "\\mathbb{H}",
        I: "\\mathbb{I}",
        J: "\\mathbb{J}",
        K: "\\mathbb{K}",
        L: "\\mathbb{L}",
        M: "\\mathbb{M}",
        N: "\\mathbb{N}",
        O: "\\mathbb{O}",
        P: "\\mathbb{P}",
        Q: "\\mathbb{Q}",
        R: "\\mathbb{R}",
        S: "\\mathbb{S}",
        T: "\\mathbb{T}",
        U: "\\mathbb{U}",
        V: "\\mathbb{V}",
        W: "\\mathbb{W}",
        X: "\\mathbb{X}",
        Y: "\\mathbb{Y}",
        Z: "\\mathbb{Z}",

        bAlpha: "\\boldsymbol{\\Alpha}",
        bBeta: "\\boldsymbol{\\beta}",
        bDelta: "\\boldsymbol{\\delta}",
        bEta: "\\boldsymbol{\\eta}",
        bGamma: "\\boldsymbol{\\Gamma}",
        bLambda: "\\boldsymbol{\\Lambda}",
        bOmega: "\\boldsymbol{\\Omega}",
        bPhi: "\\boldsymbol{\\Phi}",
        bPi: "\\boldsymbol{\\Pi}",
        bPsi: "\\boldsymbol{\\Psi}",
        bSigma: "\\boldsymbol{\\Sigma}",
        bTau: "\\boldsymbol{\\tau}",
        bXi: "\\boldsymbol{\\Xi}",
        bLambda: "\\boldsymbol{\\Lambda}",
        
        balpha: "\\boldsymbol{\\alpha}",
        bbeta: "\\boldsymbol{\\beta}",
        bepsilon: "\\boldsymbol{\\epsilon}",
        bvarepsilon: "\\boldsymbol{\\varepsilon}",
        bdelta: "\\boldsymbol{\\delta}",
        bgamma: "\\boldsymbol{\\gamma}",
        blambda: "\\boldsymbol{\\lambda}",
        bmu: "\\boldsymbol{\\mu}",
        bphi: "\\boldsymbol{\\phi}",
        bpi: "\\boldsymbol{\\pi}",
        bpsi: "\\boldsymbol{\\psi}",
        brho: "\\boldsymbol{\\rho}",
        bsigma: "\\boldsymbol{\\sigma}",
        btau: "\\boldsymbol{\\tau}",
        bxi: "\\boldsymbol{\\xi}",
        bEta: "\\boldsymbol{\\eta}",
        bPhi: "\\boldsymbol{\\Phi}",
        bPi: "\\boldsymbol{\\Pi}",
        bPsi: "\\boldsymbol{\\Psi}",
        bXi: "\\boldsymbol{\\Xi}",
        blambda: "\\boldsymbol{\\lambda}",
        bmu: "\\boldsymbol{\\mu}",
        bphi: "\\boldsymbol{\\phi}",
        bpi: "\\boldsymbol{\\pi}",
        bpsi: "\\boldsymbol{\\psi}",
        brho: "\\boldsymbol{\\rho}",
        bsigma: "\\boldsymbol{\\sigma}",
                   
        curl: ["\\left\\lbrace#1\\right\\rbrace", 1],
        floor: ["\\left\\lfloor#1\\right\\rfloor", 1],
        ceil: ["\\left\\lceil#1\\right\\rceil", 1],
        abs: ["\\left\\lvert#1\\right\\rvert", 1],
        norm: ["\\left\\lVert#1\\right\\rVert", 1],

        independent: "\\mathrel{\\perp\\!\\!\\perp}",

        var: "\\mathrm{Var}",
        cov: "\\mathrm{Cov}",
        cor: "\\mathrm{Corr}",
        diag: "\\mathrm{diag}",
        rank: "\\mathrm{rank}",
        vecc: "\\mathrm{vec}",
      }
    }
  };
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-dark"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = true;
    const queryPrefersDark = window.matchMedia('(prefers-color-scheme: dark)');
    const darkModeDefault = queryPrefersDark.matches;
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    queryPrefersDark.addEventListener("change", e => {
      if(window.localStorage.getItem("quarto-color-scheme") !== null)
        return;
      const alternate = e.matches
      toggleColorMode(alternate);
      localAlternateSentinel = e.matches ? 'alternate' : 'default'; // this is used alongside local storage!
      toggleGiscusIfUsed(alternate, darkModeDefault);
    });
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./TS01_AR1.html">Time Series</a></li><li class="breadcrumb-item"><a href="./TS04_Spurious_regression.html"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Spurious Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Metrics Notes</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Probability Refresher</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./conditional_expectation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Conditional Expectation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./measure_theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Measure Theory</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Time Series</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./TS01_AR1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">AR(1)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./TS01_AR_example.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">AR – Example</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./TS01_phillips-curve.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Phillips Curve</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./TS01_properties_AR1Errors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Properties of OLS with Serially Correlated Errors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./TS01_Correct_AR1Errors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Correcting for Serial Correaltion with Strictly Exogenous Regressors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./TS01_examples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">TS Examples</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./TS02_lag_poly.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Lag polynomials</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./TS02_AR-MA-representation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">AR(1) and Its MA representation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./TS03_finite-property.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">OLS Finite Sample Assumptions and Properties</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./TS03_OLS_identification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Estimation of Autoregressive Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./TS03_asymptotic-property.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">OLS Asymptotic Assumptions and Properties</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./TS04_TimeSeries_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Time Series Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./TS04_VAR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Vector Autoregressions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./TS04_Spurious_regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Spurious Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./TS04_highly-persistent.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Highly Persistent TS</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./TS05_Forecast.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Forecast</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Panel Data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./PA01_Pooled_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Pooled Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./PA02_Panel_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Panel Regressions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./PA03_Fixed-Effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Fixed Effects Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./PA04_Random-Effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Random Effects Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./PA05_dynamic_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Dynamic Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./PA06_dynamic_models_with_pdynmc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Dynamic Model Applications with <code>pdynmc</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./PA07_Hetero_lm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Linear Models with Heterogeneous Coefficients</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#trending-time-series" id="toc-trending-time-series" class="nav-link active" data-scroll-target="#trending-time-series"><span class="header-section-number">17.1</span> Trending Time Series</a>
  <ul class="collapse">
  <li><a href="#linear-time-trend" id="toc-linear-time-trend" class="nav-link" data-scroll-target="#linear-time-trend"><span class="header-section-number">17.1.1</span> Linear time trend</a></li>
  <li><a href="#exponential-trend" id="toc-exponential-trend" class="nav-link" data-scroll-target="#exponential-trend"><span class="header-section-number">17.1.2</span> Exponential trend</a></li>
  </ul></li>
  <li><a href="#using-trending-variables-in-regression-analysis" id="toc-using-trending-variables-in-regression-analysis" class="nav-link" data-scroll-target="#using-trending-variables-in-regression-analysis"><span class="header-section-number">17.2</span> Using Trending Variables in Regression Analysis</a></li>
  <li><a href="#computing-r-squared-when-the-dependent-variable-is-trending" id="toc-computing-r-squared-when-the-dependent-variable-is-trending" class="nav-link" data-scroll-target="#computing-r-squared-when-the-dependent-variable-is-trending"><span class="header-section-number">17.3</span> Computing R-Squared when the Dependent Variable Is Trending</a></li>
  <li><a href="#i1-process" id="toc-i1-process" class="nav-link" data-scroll-target="#i1-process"><span class="header-section-number">17.4</span> I(1) process</a>
  <ul class="collapse">
  <li><a href="#real-world-example" id="toc-real-world-example" class="nav-link" data-scroll-target="#real-world-example"><span class="header-section-number">17.4.1</span> Real World Example</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./TS01_AR1.html">Time Series</a></li><li class="breadcrumb-item"><a href="./TS04_Spurious_regression.html"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Spurious Regression</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Spurious Regression</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<!-- Chunk option settings -->
<!-- Define chunk option `max.lines` -->
<!-- controls max lines printed -->
<section id="trending-time-series" class="level2" data-number="17.1">
<h2 data-number="17.1" class="anchored" data-anchor-id="trending-time-series"><span class="header-section-number">17.1</span> Trending Time Series</h2>
<p>It is important to characterize if some series contain a time trend in order to draw causal inference using time series data. Ignoring the fact that two sequences are trending in the same or opposite directions can lead us to falsely conclude that changes in one variable are actually caused by changes in another variable. In many cases, <span class="env-green">two time series processes appear to be correlated only because they are both trending over time</span> for reasons related to other unobserved factors.</p>
<p>The phenomenon of finding a relationship between two or more trending variables simply because each is growing over time is an example of a <strong>spurious regression problem</strong>. We can add a time trend to account for the trend in explained or explanatory variables.</p>
<section id="linear-time-trend" class="level3" data-number="17.1.1">
<h3 data-number="17.1.1" class="anchored" data-anchor-id="linear-time-trend"><span class="header-section-number">17.1.1</span> Linear time trend</h3>
<p>If <span class="math inline">\(\{y_t\}\)</span> has a linear time trend, then we can formulate the series as</p>
<p><span class="math display">\[
y_t = \alpha_0 + \alpha_1 t + e_t, \; t=1, 2, \ldots,
\]</span> where <span class="math inline">\(e_t\sim iid (0, \sigma^2_e)\)</span> or a more realistic characterization allows <span class="math inline">\(\{e_t\}\)</span> to be correlated over time.</p>
<p><a href="#fig-linear_trend" class="quarto-xref">Figure&nbsp;<span>17.1</span></a> shows a simulated series with a linear time trend. The values of <span class="math inline">\(y_t\)</span> do not fall exactly on the line in due to randomness, but the expected values are on the line:</p>
<p><span class="math display">\[
\E(y_t) = \alpha_0 + \alpha_1 t .
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-linear_trend" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-pos="H" data-fig-align="center" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-linear_trend-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="TS04_Spurious_regression_files/figure-html/fig-linear_trend-1.png" id="fig-linear_trend" class="img-fluid quarto-figure quarto-figure-center anchored figure-img" data-fig-pos="H" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-linear_trend-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17.1
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="exponential-trend" class="level3" data-number="17.1.2">
<h3 data-number="17.1.2" class="anchored" data-anchor-id="exponential-trend"><span class="header-section-number">17.1.2</span> Exponential trend</h3>
<p>When a series has the same average growth rate from period to period, we say that the time series has an exponential trend.</p>
<p>I practice, an exponential trend in a time series is captured by modelling the natural logarithm of the series as linear trend (assuming that <span class="math inline">\(y_t&gt;0\)</span>):</p>
<p><span id="eq-log_rate"><span class="math display">\[
\log (y_t) = \beta_0 + \beta_1 t + e_t, \; t=1, 2, \ldots.
\tag{17.1}\]</span></span></p>
<p>Recall that, for small changes, <span class="math inline">\(\Delta \log(y_t) = \log(y_t) - \log(y_{t-1})\)</span> is approximately the proportionate change in <span class="math inline">\(y_t:\)</span></p>
<p><span class="math display">\[
\beta_1 = \Delta \log(y_t) \approx \frac{y_t-y_{t-1}}{y_{t-1}}
\]</span></p>
<p><span class="math inline">\(\beta_1\)</span> is interpreted as the growth rate in <span class="math inline">\(y\)</span> from period <span class="math inline">\(t-1\)</span> to period <span class="math inline">\(t\)</span>. In other words, <span class="math inline">\(\beta_1\)</span> is approximately the average per period growth rate in <span class="math inline">\(y_t.\)</span></p>
<p>For example, if <span class="math inline">\(t\)</span> denotes year and <span class="math inline">\(\beta_1 = .027,\)</span> then <span class="math inline">\(y_t\)</span> grows about 2.7% per year on average.</p>
<p>Exponentiating (<a href="#eq-log_rate" class="quarto-xref"><span>17.1</span></a>) shows that <span class="math inline">\(y_t\)</span> itself has an exponential trend:</p>
<p><span class="math display">\[
y_t = \exp (\beta_0 + \beta_1 t + e_t) .
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-exp_growth" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-pos="H" data-fig-align="center" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-exp_growth-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="TS04_Spurious_regression_files/figure-html/fig-exp_growth-1.png" id="fig-exp_growth" class="img-fluid quarto-figure quarto-figure-center anchored figure-img" data-fig-pos="H" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-exp_growth-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17.2
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-exp_growth" class="quarto-xref">Figure&nbsp;<span>17.2</span></a> show a simulated time series with an exponential trend. In the early years, we see that the change in <span class="math inline">\(y_t\)</span> over each year is relatively small, whereas the change increases as time passes. This is consistent with a <em>constant average growth rate</em>: the percentage change is roughly the same in each period.</p>
</section>
</section>
<section id="using-trending-variables-in-regression-analysis" class="level2" data-number="17.2">
<h2 data-number="17.2" class="anchored" data-anchor-id="using-trending-variables-in-regression-analysis"><span class="header-section-number">17.2</span> Using Trending Variables in Regression Analysis</h2>
<p>For concreteness, consider a model where two observed factors, <span class="math inline">\(x_{t1}\)</span> and <span class="math inline">\(x_{t2}\)</span>, affect <span class="math inline">\(y_t\)</span>. In addition, there are unobserved factors that are systematically growing or shrinking over time. A model that captures this is</p>
<p><span id="eq-regression_time_trend"><span class="math display">\[
y_t = \beta_0 + \beta_1x_{t1} + \beta_2x_{t2} + \beta_3t + u_t  .
\tag{17.2}\]</span></span> This fits into the multiple linear regression framework with <span class="math inline">\(x_{t3}=t.\)</span></p>
<p>Allowing for the trend <span class="math inline">\(t\)</span> in this equation explicitly recognizes that <span class="math inline">\(y_t\)</span> may be growing (<span class="math inline">\(\beta_3&gt;0\)</span>) or shrinking (<span class="math inline">\(\beta_3&lt;0\)</span>) over time for reasons essentially unrelated to <span class="math inline">\(x_{t1}\)</span> and <span class="math inline">\(x_{t2}.\)</span> Omiiting <span class="math inline">\(t\)</span> from the regression and regressing <span class="math inline">\(y_t\)</span> on <span class="math inline">\(x_{t1}\)</span> and <span class="math inline">\(x_{t2}\)</span> will generally yield biased estimators of <span class="math inline">\(\beta_1\)</span> and <span class="math inline">\(\beta_2.\)</span> This is especially true if <span class="math inline">\(x_{t1}\)</span> and <span class="math inline">\(x_{t2}\)</span> are themselves trending, because they can then be highly correlated with <span class="math inline">\(t.\)</span></p>
<p><strong>Frisch–Waugh–Lovell theorem Interpretation</strong></p>
<p>Based on the Frisch–Waugh–Lovell theorem, <a href="#eq-regression_time_trend" class="quarto-xref">Equation&nbsp;<span>17.2</span></a> can have an alternative interpretation in terms of detrending the original data series before using them in regression analysis.</p>
<p><span class="math inline">\(\hat{\beta}_1\)</span> and <span class="math inline">\(\hat{\beta}_2\)</span> can be obtained in a two-step procedure as follows.</p>
<ol type="i">
<li><p>Regress <strong>each</strong> of <span class="math inline">\(y_t\)</span>, <span class="math inline">\(x_{1t}\)</span>, and <span class="math inline">\(x_{2t}\)</span> on a constant and the time trend <span class="math inline">\(t\)</span> and save the residuals, say, <span class="math inline">\(\ddot{y}_t\)</span>, <span class="math inline">\(\ddot{x}_{1t}\)</span>, <span class="math inline">\(\ddot{x}_{2t}\)</span>, <span class="math inline">\(t = 1, 2, \ldots, T\)</span>.</p>
<p>For example,</p>
<p><span class="math display">\[
\ddot{y}_t = y_t - \hat{\alpha}_0 - \hat{\alpha}_1 t.
\]</span></p>
<p>Thus, we can think of <span class="math inline">\(\ddot{y}_t\)</span> as being <em>linearly detrended</em>. In detrending <span class="math inline">\(y_t\)</span>, we have estimated the model</p>
<p><span class="math display">\[
y_t = \alpha_0 + \alpha_1 t + e_t
\]</span></p>
<p>by OLS; the residuals from this regression, <span class="math inline">\(\hat{e}_t = \ddot{y}_t\)</span>, have the time trend removed (at least in the sample). A similar interpretation holds for <span class="math inline">\(\ddot{x}_{1t}\)</span> and <span class="math inline">\(\ddot{x}_{2t}\)</span>.</p>
<p>Any potential trends in the dependent and independent variables were removed by now.</p></li>
<li><p>Run the regression of <span class="math display">\[
    \ddot{y}_t \text{ on } \ddot{x}_{1t}, \ddot{x}_{2t}.
    \]</span> (No intercept is necessary, but including an intercept affects nothing: the intercept will be estimated to be zero.) This regression exactly yields <span class="math inline">\(\hat{\beta}_1\)</span> and <span class="math inline">\(\hat{\beta}_2\)</span> from (<a href="#eq-regression_time_trend" class="quarto-xref"><span>17.2</span></a>).</p></li>
</ol>
<p>This means that the estimates of primary interest, <span class="math inline">\(\hat{\beta}_1\)</span> and <span class="math inline">\(\hat{\beta}_2\)</span>, can be interpreted as coming from a regression <em>without</em> a time trend, but where we first detrend the dependent variable and other independent variables. The same conclusion holds with any number of independent variables and if the trend is quadratic or of some other polynomial degree.</p>
<p>If <span class="math inline">\(t\)</span> is omitted from (<a href="#eq-regression_time_trend" class="quarto-xref"><span>17.2</span></a>), then no detrending occurs, and <span class="math inline">\(y_t\)</span> might seem to be related to one or more of the <span class="math inline">\(x_{jt}\)</span> simply because each contains a trend. If the time trend is statistically significant, and the results change in important ways when a time trend is added to a regression, then the initial results without a trend should be treated with suspicion.</p>
<p>The interpretation of <span class="math inline">\(\hat{\beta}_1\)</span> and <span class="math inline">\(\hat{\beta}_2\)</span> shows that it is a good idea to include a trend in the regression if any independent variable is trending, even if <span class="math inline">\(y_t\)</span> is not. If <span class="math inline">\(y_t\)</span> has no noticeable trend, but, say, <span class="math inline">\(x_{1t}\)</span> is growing over time, then excluding a trend from the regression may make it look as if <span class="math inline">\(x_{1t}\)</span> has no effect on <span class="math inline">\(y_t\)</span>, even though movements of <span class="math inline">\(x_{1t}\)</span> about its trend may affect <span class="math inline">\(y_t\)</span>. This will be captured if <span class="math inline">\(t\)</span> is included in the regression.</p>
<p>Time series exhibiting a time trend can have seasonal patterns as well, in which case we should estimate a regression model with a time trend and seasonal dummy variables. The seasonal dummies should be one less than the distinct seasonal patterns. For example, if we observe quarterly differences, we may introduce three seasonal dummies, the one left out would be the base level, represented by the intercept. The regressions can then be interpreted as regressions using both detrended and deseasonalized series.</p>
</section>
<section id="computing-r-squared-when-the-dependent-variable-is-trending" class="level2" data-number="17.3">
<h2 data-number="17.3" class="anchored" data-anchor-id="computing-r-squared-when-the-dependent-variable-is-trending"><span class="header-section-number">17.3</span> Computing R-Squared when the Dependent Variable Is Trending</h2>
<p><em>R-squareds in time series regressions are often very high, especially compared with typical R-squareds for cross-sectional data.</em> Does this mean that we learn more about factors affecting <span class="math inline">\(y\)</span> from time series data? Not necessarily. On one hand, time series data often come in aggregate form (such as average hourly wages in the U.S. economy), and aggregates are often easier to explain than outcomes on individuals, families, or firms, which is often the nature of cross-sectional data. But the usual and adjusted <span class="math inline">\(R\)</span>-squareds for time series regressions can be <span class="env-green">artificially high when the dependent variable is trending</span>.</p>
<p>Remember that <span class="math inline">\(R^2\)</span> is a measure of how large the error variance is relative to the variance of <span class="math inline">\(y\)</span>. The formula for the adjusted <span class="math inline">\(R\)</span>-squared shows this directly:</p>
<p><span class="math display">\[
\bar{R}^2 = 1 - (\hat{\sigma}_u^2 / \hat{\sigma}_y^2),
\]</span></p>
<p>where <span class="math inline">\(\hat{\sigma}_u^2\)</span> is the unbiased estimator of the error variance, <span class="math inline">\(\hat{\sigma}_y^2 = \text{SST}/(n - 1)\)</span>, and <span class="math inline">\(\text{SST} = \sum_{t=1}^n (y_t - \bar{y})^2\)</span>. Now, estimating the error variance when <span class="math inline">\(y_t\)</span> is trending is no problem, provided a time trend is included in the regression. However, when <span class="math inline">\(E(y_t)\)</span> follows, say, a linear time trend, <span class="math inline">\(\text{SST}/(n - 1)\)</span> is <span class="env-orange">NO longer an unbiased or consistent estimator</span> of <span class="math inline">\(\text{Var}(y_t)\)</span>. In fact, <span class="math inline">\(\text{SST}/(n - 1)\)</span> can <span class="env-green">substantially overestimate the variance</span> in <span class="math inline">\(y_t\)</span>, because it <span class="env-orange">does NOT account for the trend</span> in <span class="math inline">\(y_t\)</span>.</p>
<p>When the dependent variable satisfies linear, quadratic, or any other polynomial trends, it is easy to compute a goodness-of-fit measure that first nets out the effect of any time trend on <span class="math inline">\(y_t\)</span>. The simplest method is to compute the usual <span class="math inline">\(R\)</span>-squared in a regression where the dependent variable has already been detrended. For example, if the model is <span class="math display">\[
y_t = \beta_0 + \beta_1x_{t1} + \beta_2x_{t2} + \beta_3t + u_t  ,
\]</span> then we first detrend <span class="math inline">\(y_t\)</span> by regressing <span class="math inline">\(y_t\)</span> on <span class="math inline">\(t\)</span>:</p>
<p><span id="eq-detrend_y"><span class="math display">\[
y_t = \alpha_0 + \alpha_1 t + e_t
\tag{17.3}\]</span></span> and obtain the residuals <span class="math inline">\(\hat{e}_t = \ddot{y}_t\)</span>. Then, we regress <span class="math inline">\(\ddot{y}_t\)</span> on <span class="math inline">\(x_{t1},\)</span> <span class="math inline">\(x_{t2},\)</span> and <span class="math inline">\(t\)</span>:</p>
<p><span class="math display">\[
\ddot{y}_t = \beta_0 + \beta_1 x_{t1} + \beta_2 x_{t2} + \beta_3 t + u_t .
\]</span></p>
<p>The <span class="math inline">\(R\)</span>-squared from this regression is</p>
<p><span id="eq-R2_time"><span class="math display">\[
R^2 = 1 - \frac{\text{SSR}}{\sum_{t=1}^n \ddot{y}_t^2},
\tag{17.4}\]</span></span></p>
<p>where SSR is identical to the sum of squared residuals from <span id="eq-original_model"><span class="math display">\[
\hat{y}_t = \hat{\beta}_0 + \hat{\beta}_1x_{t1} + \hat{\beta}_2x_{t2} + \hat{\beta}_3t .
\tag{17.5}\]</span></span></p>
<p>Since <span class="math inline">\(\sum_{t=1}^n \ddot{y}_t^2 \leq \sum_{t=1}^n (y_t - \bar{y})^2\)</span> (and usually the inequality is strict), the <span class="math inline">\(R\)</span>-squared from (<a href="#eq-R2_time" class="quarto-xref"><span>17.4</span></a>) is no greater than, and usually less than, the <span class="math inline">\(R\)</span>-squared from (<a href="#eq-original_model" class="quarto-xref"><span>17.5</span></a>). (The sum of squared residuals is identical in both regressions.) When <span class="math inline">\(y_t\)</span> contains a strong linear time trend, (<a href="#eq-R2_time" class="quarto-xref"><span>17.4</span></a>) can be much less than the usual <span class="math inline">\(R\)</span>-squared.</p>
<p>The R-squared in (<a href="#eq-R2_time" class="quarto-xref"><span>17.4</span></a>) better reflects how well <span class="math inline">\(x_{t1}\)</span> and <span class="math inline">\(x_{t2}\)</span> explain <span class="math inline">\(y_t\)</span> because it nets out the effect of the time trend.</p>
<p>An <strong>adjusted R-squared</strong> can also be computed based on (<a href="#eq-R2_time" class="quarto-xref"><span>17.4</span></a>).</p>
<p><span class="math display">\[
\overline{R}^2 = 1 - \frac{\text{SSR}/(n-K)}{\sum_{t=1}^n \ddot{y}_t^2 / (n-p)},
\]</span> where <span class="math inline">\(K\)</span> is the <span class="math inline">\(df\)</span> in the usual regression (<a href="#eq-original_model" class="quarto-xref"><span>17.5</span></a>) (that includes any time trends), and <span class="math inline">\(p\)</span> is the number of trend parameters estimated in detrending <span class="math inline">\(y_t.\)</span></p>
<p>In our example model (<a href="#eq-regression_time_trend" class="quarto-xref"><span>17.2</span></a>), we divide <span class="math inline">\(SSR\)</span> by <span class="math inline">\((n-4)\)</span> and divide <span class="math inline">\(\sum_{t=1}^n \ddot{y}_t^2\)</span> by <span class="math inline">\((n-2),\)</span> as there are two trend parameters estimated in detrending <span class="math inline">\(y_t\)</span> (<a href="#eq-detrend_y" class="quarto-xref"><span>17.3</span></a>).</p>
</section>
<section id="i1-process" class="level2" data-number="17.4">
<h2 data-number="17.4" class="anchored" data-anchor-id="i1-process"><span class="header-section-number">17.4</span> I(1) process</h2>
<p>When we are dealing with integrated processes of order one, there is an additional complication. Even if the two series have means that are not trending, a simple regression involving two independent <span class="math inline">\(\mathrm I(1)\)</span> series will often result in a significant <span class="math inline">\(t\)</span> statistic. To be more precise, let <span class="math inline">\(\{x_t\}\)</span> and <span class="math inline">\(\{y_t\}\)</span> be random walks generated by</p>
<p><span class="math display">\[
x_t = x_{t-1} + a_t, \; t=2,3,\ldots,
\]</span> and <span class="math display">\[
y_t = y_{t-1} + e_t, \; t=2,3,\ldots,
\]</span> where <span class="math inline">\(\{a_t\}\)</span> and <span class="math inline">\(\{e_t\}\)</span> are iid innovations, with mean zero and variances <span class="math inline">\(\sigma^2_a\)</span> and <span class="math inline">\(\sigma^2_e,\)</span> respectively.</p>
<p>Assume further that <span class="math inline">\(\{a_t\}\)</span> and <span class="math inline">\(\{e_t\}\)</span> are independent processes. This implies that <span class="math inline">\(\{x_t\}\)</span> and <span class="math inline">\(\{y_t\}\)</span> are also independent. But if we run the simple regression</p>
<p><span class="math display">\[
y_t = \beta_0 + \beta_1 x_t + u_t
\]</span> and obtain the usual <span class="math inline">\(t\)</span> statistic for <span class="math inline">\(\hat{\beta}_1\)</span> and the usual R-squared, the results cannot be interpreted as if the variables are stationary (<span class="math inline">\(\mathrm I(0)\)</span>).</p>
<ul>
<li><p>The <span class="math inline">\(t\)</span> statistic will be significant a large percentage of the time, much larger than the nominal significance level. <span class="math inline">\(\rightarrow\)</span> This is called the <span class="env-orange">spurious regression</span> problem, where <span class="math inline">\(y_t\)</span> and <span class="math inline">\(x_t\)</span> are independent, but an OLS regression indicates a significant <span class="math inline">\(t\)</span> statistic.</p>
<p>For the <span class="math inline">\(t\)</span> statistic of <span class="math inline">\(\hat{\beta}_1\)</span> to have an approximate standard normal distribution in large samples, at a minimum, <span class="math inline">\(\{u_t\}\)</span> should be a mean zero, serially uncorrelated process. But under <span class="math display">\[
  \mathrm H_0: \beta_1=0, y_t = \beta_0 + u_t
  \]</span> the assumption was violated.</p>
<p>To see this, we assume the initial value <span class="math inline">\(y_1=0\)</span>, then under <span class="math inline">\(\mathrm H_0\)</span> we have <span class="math inline">\(\beta_0=0,\)</span> and <span class="math display">\[
  u_t = y_t = \sum_{j=1}^t e_j.
  \]</span> In other words, <span class="math inline">\(\{u_t\}\)</span> is a random walk under <span class="math inline">\(\mathrm H_0\)</span> which clearly violate even the asymptotic version of the Gauss-Markov assumptions.</p></li>
<li><p>Including a time trend does NOT necessarily change the conclusion.</p>
<p>If <span class="math inline">\(y_t\)</span> or <span class="math inline">\(x_t\)</span> is a random walk with drift and a time trend is NOT included, then spurious regression problem is even worse.</p></li>
<li><p>The behavior of R-squared is nonstandard.</p>
<p>In regressions with <span class="math inline">\(\mathrm I(0)\)</span> time series variables, the R-squared converges in probability to the population R-squared: <span class="math inline">\(1-\sigma^2_u/\sigma^2_y.\)</span></p>
<p>But in regressions with <span class="math inline">\(\mathrm I(1)\)</span> processes, rather than the R-squared having a well-defined plim, it actually converges to a <em>random variable</em>. Formalizing this notion is well beyond the scope of this text.</p>
<p>The implication is that the R-squared is large with high probability, even though <span class="math inline">\(y_t\)</span> and <span class="math inline">\(x_t\)</span> are independent time series processes.</p></li>
</ul>
<p>The same considerations arise with multiple independent variables, each of which may be <span class="math inline">\(\mathrm I(1)\)</span> or some of which may be <span class="math inline">\(\mathrm I(0)\)</span>. If <span class="math inline">\(y_t\)</span> is <span class="math inline">\(\mathrm I(1)\)</span> and at least some of the explanatory variables are <span class="math inline">\(\mathrm I(1)\)</span>, the regression results may be spurious.</p>
<p>This does not mean that regressions involving any <span class="math inline">\(\mathrm I(1)\)</span> process are problematic. There are remedies for using the <span class="math inline">\(\mathrm I(1)\)</span> processes:</p>
<ul>
<li><p>The first difference of an <span class="math inline">\(\mathrm I(1)\)</span> process can be used to transform it to be weakly dependent (and often stationary) – <span class="env-green"><strong>Error Correction Model</strong></span>.</p>
<p>For example <span class="math display">\[
\Delta y_t = \mu + \beta_1 \Delta x_t + \delta (y_{t-1} - \theta x_{t-1}) + \varepsilon_t,
\]</span></p>
<p>where <span class="math inline">\(\delta&lt;0.\)</span></p>
<p>See <a href="TS04_highly-persistent.html#sec-ecm" class="quarto-xref"><span>Section 18.4</span></a> for more details on error correction models.</p></li>
<li><p>Regressing an <span class="math inline">\(\mathrm I(1)\)</span> dependent variable on an <span class="math inline">\(\mathrm I(1)\)</span> independent variable can be informative, but only if these variables contain a common stochastic trend, that is, the series are said to be <span class="env-green"><strong>Cointegrated</strong></span>.</p></li>
</ul>
<section id="real-world-example" class="level3" data-number="17.4.1">
<h3 data-number="17.4.1" class="anchored" data-anchor-id="real-world-example"><span class="header-section-number">17.4.1</span> Real World Example</h3>
<section id="example-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="example-1">Example 1</h4>
<p>We have two time series:</p>
<ul>
<li><code>UNRATE</code>: the U.S. unemployment rate.</li>
<li><code>LN_JAP_IP</code>: logged Japanese industrial production</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">"data/spurious_reg.xlsx"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data)[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="st">"year-quarter"</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 232 × 3
   `year-quarter`   UNRATE LN_JAP_IP
   &lt;chr&gt;             &lt;dbl&gt;     &lt;dbl&gt;
 1 1960:01        5.133333  2.500159
 2 1960:02        5.233333  2.539725
 3 1960:03        5.533333  2.581925
 4 1960:04        6.266667  2.628351
 5 1961:01        6.8       2.682107
 6 1961:02        7         2.720609
 7 1961:03        6.766667  2.764591
 8 1961:04        6.2       2.798435
 9 1962:01        5.633333  2.831171
10 1962:02        5.533333  2.831171
# ℹ 222 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>qtr_index <span class="ot">&lt;-</span> <span class="fu">as.yearqtr</span>(data<span class="sc">$</span><span class="st">`</span><span class="at">year-quarter</span><span class="st">`</span>, <span class="at">format =</span> <span class="st">"%Y:%q"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>qtr_xts <span class="ot">&lt;-</span> <span class="fu">xts</span>(data[<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>)], qtr_index)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(qtr_xts, <span class="at">facets =</span> Series <span class="sc">~</span> .) <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_grid</span>(Series <span class="sc">~</span> ., <span class="at">scales =</span> <span class="st">"free_y"</span>) <span class="sc">+</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_vline</span>(</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">xintercept =</span> <span class="fu">as.yearqtr</span>(<span class="st">"1985 Q4"</span>),</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">linetype =</span> <span class="st">"dashed"</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"UNRATE"</span> <span class="ot">=</span> <span class="st">"darkred"</span>, <span class="st">"LN_JAP_IP"</span> <span class="ot">=</span> <span class="st">"#3B4992FF"</span>)) <span class="sc">+</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_x_yearqtr</span>(<span class="at">format =</span> <span class="st">"%Y-Q%q"</span>) <span class="sc">+</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="TS04_Spurious_regression_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-fig-pos="H" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>data1 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="st">`</span><span class="at">year-quarter</span><span class="st">`</span> <span class="sc">&lt;=</span> <span class="st">"1985:4"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(UNRATE <span class="sc">~</span> LN_JAP_IP, <span class="at">data =</span> data1) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = UNRATE ~ LN_JAP_IP, data = data1)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.6120 -1.1004  0.0557  0.8909  3.7861 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   0.4576     1.0096   0.453    0.651    
LN_JAP_IP     1.5148     0.2678   5.656 1.43e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.5 on 102 degrees of freedom
Multiple R-squared:  0.2387,    Adjusted R-squared:  0.2313 
F-statistic: 31.98 on 1 and 102 DF,  p-value: 1.425e-07</code></pre>
</div>
</div>
<p>Run the regression on data from 1960 to 1985, we obtain the following estimation.</p>
<p><span id="eq-before1986"><span class="math display">\[
\begin{aligned}
\widehat{\text{UNRATE}}_t &amp;= 0.46 + 1.51 \times \text{LN\_JAP\_IP}, R^2 = 0.24  \\
&amp;\phantom{=} \;(1.01) \;\; (0.27)
\end{aligned}
\tag{17.6}\]</span></span></p>
<p>The <span class="math inline">\(t\)</span>-statistic on the slope coefficient is 5.66, which shows statistical significant positive relationship.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>data2 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="st">`</span><span class="at">year-quarter</span><span class="st">`</span> <span class="sc">&gt;</span> <span class="st">"1985:4"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(UNRATE <span class="sc">~</span> LN_JAP_IP, <span class="at">data =</span> data2) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = UNRATE ~ LN_JAP_IP, data = data2)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.8231 -0.9812 -0.3774  0.6837  3.8549 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   42.371      7.745   5.471 2.32e-07 ***
LN_JAP_IP     -7.923      1.686  -4.698 6.76e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.363 on 126 degrees of freedom
Multiple R-squared:  0.1491,    Adjusted R-squared:  0.1423 
F-statistic: 22.07 on 1 and 126 DF,  p-value: 6.756e-06</code></pre>
</div>
</div>
<p>Running the regression using data from 1986 to 2017, we obtain</p>
<p><span id="eq-after1986"><span class="math display">\[
\begin{aligned}
\widehat{\text{UNRATE}}_t &amp;= 42.37 - 7.92 \times \text{LN\_JAP\_IP}, R^2 = 0.15  \\
&amp;\phantom{=} \;(7.74) \;\; (1.69)
\end{aligned}
\tag{17.7}\]</span></span></p>
<p>which shows significant negative relationship btw the two series.</p>
<p>Q: Why <a href="#eq-before1986" class="quarto-xref">Equation&nbsp;<span>17.6</span></a> and <a href="#eq-after1986" class="quarto-xref">Equation&nbsp;<span>17.7</span></a> generate so different yet both significant coefficient estimates?<br>
A: The source of these conflicting results is that both series have stochastic trends. These trends happened to align from 1960 through 1985 but were reversed from 1986 through 2017. There is, in fact, no compelling economic or political reason to think that the trends in these two series are related. In short, these regressions are <strong>spurious</strong>.</p>
<p><strong>Main Takeaway:</strong> OLS can be misleading when the series contain stochastic trends. More generally, if <span class="math inline">\(\{y_t\}\)</span> is <span class="math inline">\(\mathrm I(1)\)</span> and at least some of the explanatory variables are <span class="math inline">\(\mathrm I(1)\)</span>, the regression results may be spurious.</p>
<hr>
</section>
<section id="example-2" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="example-2">Example 2</h4>
<p><a href="#fig-consup_income" class="quarto-xref">Figure&nbsp;<span>17.3</span></a> plotted logs of consumption and GDP (aka Income) for 1950.Q1 to 2000.Q4.</p>
<ul>
<li><code>REALGDP</code>: <span class="math inline">\(\ln \text{GDP}\)</span></li>
<li><code>REALCONS</code>: <span class="math inline">\(\ln \text{Cons}\)</span></li>
</ul>
<p>Both variables are obviously nonstationary and appear <span class="math inline">\(\mathrm I(1)\)</span>. The figure suggests a highly significant relationship but the relationship is due to the fact that both series are trending over time. The regression results are spurious.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># data from 1950Q1 to 2000Q4</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/Greene_consump_income.csv"</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">REALGDP =</span> <span class="fu">log</span>(REALGDP),</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">REALCONS =</span> <span class="fu">log</span>(REALCONS),</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">year_quarter =</span> <span class="fu">paste</span>(YEAR, QTR, <span class="at">sep =</span> <span class="st">"-"</span>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>qtr_index <span class="ot">&lt;-</span> <span class="fu">as.yearqtr</span>(data<span class="sc">$</span>year_quarter, <span class="at">format =</span> <span class="st">"%Y-%q"</span>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>qtr_xts <span class="ot">&lt;-</span> <span class="fu">xts</span>(data[<span class="fu">c</span>(<span class="st">"REALGDP"</span>, <span class="st">"REALCONS"</span>)], qtr_index)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(qtr_xts, <span class="at">facets =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">linetype =</span> Series) <span class="sc">+</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"REALGDP"</span> <span class="ot">=</span> <span class="st">"black"</span>, <span class="st">"REALCONS"</span> <span class="ot">=</span> <span class="st">"black"</span>)) <span class="sc">+</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_linetype_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"REALGDP"</span> <span class="ot">=</span> <span class="st">"solid"</span>, <span class="st">"REALCONS"</span> <span class="ot">=</span> <span class="st">"dashed"</span>)) <span class="sc">+</span></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_x_yearqtr</span>(<span class="at">format =</span> <span class="st">"%Y-Q%q"</span>) <span class="sc">+</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Logs"</span>) <span class="sc">+</span> </span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position =</span> <span class="fu">c</span>(<span class="fl">0.1</span>, <span class="fl">0.8</span>),</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.title =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-consup_income" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-pos="H" data-fig-align="center" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-consup_income-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="TS04_Spurious_regression_files/figure-html/fig-consup_income-1.png" id="fig-consup_income" class="img-fluid quarto-figure quarto-figure-center anchored figure-img" data-fig-pos="H" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-consup_income-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17.3
</figcaption>
</figure>
</div>
</div>
</div>
<p>Unrestricted model:</p>
<p><span class="math display">\[
y_t = \mu + \gamma_1 y_{t-1} + \beta_0 x_t + \beta_1 x_{t-1} + \varepsilon_t,
\]</span></p>
<p>The Error Correction Model:</p>
<p><span class="math display">\[
\Delta y_t = \mu + \beta_0 \Delta x_{t} + (\gamma_1 - 1)(y_{t_1} - \theta x_{t-1}) + \varepsilon_t.
\]</span></p>
<ul>
<li>Equilibrium relationship: <span class="math inline">\(\Delta y_t = \mu + \beta_0 \Delta x_{t} + \varepsilon_t\)</span>, where <span class="math inline">\(\varepsilon_t\)</span> is the equilibrium error.</li>
<li>Error correction term: <span class="math inline">\((\gamma_1 - 1)(y_{t_1} - \theta x_{t-1})\)</span></li>
</ul>
<p>The standard approach is the Engle-Granger two-step method:</p>
<ol type="1">
<li>Run the cointegrating regression of <span class="math inline">\(y_t\)</span> on <span class="math inline">\(x_t\)</span> and save the residuals, <span class="math inline">\(\hat{s}_t = y_t - \hat{\theta} x_t\)</span>.</li>
<li>Run the regression of <span class="math inline">\(\Delta y_t\)</span> on <span class="math inline">\(\Delta x_t\)</span> and <span class="math inline">\(\hat{s}_{t-1}\)</span> (the lagged residual is the error-correction term <span class="math inline">\(y_{t-1}-\hat{\theta}x_{t-1}\)</span>).</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: cointegrating regression</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>coint_reg <span class="ot">&lt;-</span> <span class="fu">lm</span>(REALCONS <span class="sc">~</span> REALGDP, <span class="at">data =</span> data)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>ecm_term <span class="ot">&lt;-</span> <span class="fu">residuals</span>(coint_reg) <span class="co"># v_hat_t = y_t - theta*x_t</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(coint_reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = REALCONS ~ REALGDP, data = data)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.038885 -0.010280  0.000642  0.009570  0.065623 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.904107   0.019974  -45.26   &lt;2e-16 ***
REALGDP      1.056765   0.002399  440.53   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.01667 on 202 degrees of freedom
Multiple R-squared:  0.999, Adjusted R-squared:  0.999 
F-statistic: 1.941e+05 on 1 and 202 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The cointegrating regression shows that the estimated cointegrating parameter is 1.057, given by</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{\ln\text{Cons}}_t &amp;= -0.9 + 1.057 \times \ln\text{GDP}_t, \\
&amp;\phantom{=} \qquad\qquad (0.002)
\end{aligned}
\]</span></p>
<p>which captures the long-run relationship between consumption and income.</p>
<p>Hence, the residuals from the cointegrating regression can be obtained by</p>
<p><span class="math display">\[
\hat{s}_t = \ln\text{Cons}_t - (-0.9 + 1.057 \times \ln\text{GDP}_t) .
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot cointegrating regression residuals</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>ecm_xts <span class="ot">&lt;-</span> <span class="fu">xts</span>(data<span class="sc">$</span>ecm_term, qtr_index)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(ecm_xts) <span class="sc">+</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"gray50"</span>) <span class="sc">+</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="cn">NULL</span>, <span class="at">title =</span> <span class="st">"Cointegrating Regression Residuals"</span>) <span class="sc">+</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_x_yearqtr</span>(<span class="at">format =</span> <span class="st">"%Y-Q%q"</span>) <span class="sc">+</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="TS04_Spurious_regression_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-fig-pos="H" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The residuals shows the absence of a time trend. But, it remains to verify whether the series of residuals is stationary.</p>
<p>We use ADF test to check the stationarity of the residuals.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(urca)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>adf_res <span class="ot">&lt;-</span> <span class="fu">ur.df</span>(data<span class="sc">$</span>ecm_term, <span class="at">type =</span> <span class="st">"drift"</span>, <span class="at">lags =</span> <span class="dv">1</span>)  <span class="co"># no intercept</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(adf_res)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression drift 


Call:
lm(formula = z.diff ~ z.lag.1 + 1 + z.diff.lag)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.041195 -0.004861 -0.000272  0.004721  0.021621 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.0003257  0.0005817  -0.560    0.576    
z.lag.1     -0.1615118  0.0370205  -4.363 2.06e-05 ***
z.diff.lag  -0.0985225  0.0677316  -1.455    0.147    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.008261 on 199 degrees of freedom
Multiple R-squared:   0.11, Adjusted R-squared:  0.1011 
F-statistic:  12.3 on 2 and 199 DF,  p-value: 9.186e-06


Value of test-statistic is: -4.3628 9.6418 

Critical values for test statistics: 
      1pct  5pct 10pct
tau2 -3.46 -2.88 -2.57
phi1  6.52  4.63  3.81</code></pre>
</div>
</div>
<p>The ADF regression of the least squares residuals on a constant (random walk with drift), the lagged value, and the lagged first difference shows that</p>
<p><span class="math display">\[
\widehat{\Delta \hat{s}}_t = -0.0003 - 0.162 \hat{s}_{t-1} -0.099 \Delta \hat{s}_{t-1},
\]</span></p>
<p>the <span class="math inline">\(t\)</span>-statistic on the lagged level of the residuals is <span class="math inline">\(-0.162,\)</span> which is statistically significant at the 5% level, and the ADF test statistics are <span class="math inline">\(DF_{\tau} = -4.36\)</span> and <span class="math inline">\(DF_{\gamma} = 9.64\)</span>, which are both significant at the 1% level. This suggests that the residuals are stationary, and thus, there is a long-run relationship between consumption and income. We conclude that the two series are cointegrated, and we can proceed to estimate the error correction model.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: ECM</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">d_REALCONS =</span> REALCONS <span class="sc">-</span> <span class="fu">lag</span>(REALCONS),</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">d_REALGDP  =</span> REALGDP <span class="sc">-</span> <span class="fu">lag</span>(REALGDP),</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">ecm_lag    =</span> <span class="fu">lag</span>(ecm_term) <span class="co"># s_hat_{t-1}</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>ecm_fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(d_REALCONS <span class="sc">~</span> d_REALGDP <span class="sc">+</span> ecm_lag, <span class="at">data =</span> data)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ecm_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = d_REALCONS ~ d_REALGDP + ecm_lag, data = data)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.039858 -0.003276  0.000140  0.004081  0.028833 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.0037844  0.0006561   5.768 3.01e-08 ***
d_REALGDP    0.5823641  0.0510053  11.418  &lt; 2e-16 ***
ecm_lag     -0.0951092  0.0305075  -3.118  0.00209 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.006925 on 200 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.3947,    Adjusted R-squared:  0.3886 
F-statistic:  65.2 on 2 and 200 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The estimated error correction model, with estimated standard errors in parentheses, is</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{\Delta \ln\text{Cons}_t} &amp;= 0.004 + 0.582 \times \Delta \ln\text{GDP}_t + (0.905-1) \times (REALCONS - 1.057 \times REALGDP) \\
&amp;\phantom{=} \;(0.00066) \;\; (0.05) \qquad\qquad\qquad\qquad (0.03)
\end{aligned}
\]</span></p>
<p>When the deviation is positive, multiplying it by <span class="math inline">\((\gamma_1 - 1) = -0.095\)</span> gives a negative number, indicating a negative adjustment. This means that if consumption is above its equilibrium level, it will tend to decrease in the next period.</p>
<p>By contrast, if consumption is below its equilibrium level (negative deviation), it will tend to increase in the next period.</p>
<p>The estimated error correction term is statistically significant, which suggests that there is a long-run relationship between consumption and income, and that deviations from this long-run relationship are corrected over time.</p>
<hr>
<p><strong>References:</strong></p>
<ul>
<li>Chapter 18.3 Spurious Regression, Stock, James H., and Mark W. Watson. 2019. Introduction to Econometrics. 4th ed.&nbsp;Pearson Education Limited.</li>
</ul>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./TS04_VAR.html" class="pagination-link" aria-label="Vector Autoregressions">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Vector Autoregressions</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./TS04_highly-persistent.html" class="pagination-link" aria-label="Highly Persistent TS">
        <span class="nav-page-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Highly Persistent TS</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>